### ISSUE TITLE
Bot need to reset the list

### ISSUE THREAD

**Issue by sparta15** [palmerabollo/bot-food#1]
We need to reset the list when the dinner is finished or at 00:00

**Comment by palmerabollo** [comment]
Yes. DynamoDB is supposed to do it automatically. We don't need to code it.
Let me check its config before reinventing the wheel.

**Comment by palmerabollo** [comment]
You need to add a creation timestamp to the dynamodb record (a number in epoch format).
This commit includes a `created_at` field https://github.com/palmerabollo/bot-food/commit/86c3229525a08c847552d61d683fedca4131141a
